language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install -Pcoverage,qulice --batch-mode --errors
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - TRAVIS_DIR="$TRAVIS_BUILD_DIR/.travis"
deploy:
  -
    provider: script
    script: sh $TRAVIS_DIR/publish.sh
    on:
      repo: opentangerine/ot-watch
      branch: master
  -
    provider: script
    script: sh $TRAVIS_DIR/publish.sh
    on:
      repo: opentangerine/ot-watch
      tags: true