language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - echo COMPILE
  - echo $TRAVIS_DIR
  - echo $TRAVIS_BUILD_DIR/.travis
#  - mvn clean install -Pcoverage,qulice --batch-mode --errors
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - TRAVIS_DIR="$TRAVIS_BUILD_DIR/.travis"
deploy:
  -
    provider: script
    script: $TRAVIS_DIR/publish.sh
    on:
      repo: opentangerine/ot-watch
      branch: master
  -
    provider: script
    script: $TRAVIS_DIR/publish.sh
    on:
      repo: opentangerine/ot-watch
      tags: true